name: tri_karo_2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  get_storage: ^2.0.3
  google_sign_in: ^5.4.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  google_fonts: ^3.0.1
  eva_icons_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  awesome_snackbar_content: ^0.1.0
  loader_overlay: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
